### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by kaptk2** [tighten/quicksand#34]
This package is not install-able with PHP8, are there any plans to bump the version requirement?

**Comment by imjohnbon** [comment]
Hi @kaptk2, thanks for bringing this issue to our attention. I'm looking into adding PHP8 support to Quicksand right now.

**Comment by imjohnbon** [comment]
Hey @kaptk2, we just released version `2.4.2` which includes support for PHP 8. I'm going to close out this issue now, but feel free to open up a new one if you have any issues.
