### ISSUE TITLE
Delectables array order affect something?

### ISSUE THREAD

**Issue by tkferd** [tighten/quicksand#38]
Does the order of models included in the `delectables` array make difference?

Also, my database has self-related tables and I need a way to delete these records without giving an error. How can I do that?

**Self-related tables error**
````
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`salutis`.`entry`, CONSTRAINT `entry_entry_id_foreign` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`)) (SQL: delete from `entry` where `deleted_at` < 2022-02-02 08:22:39)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

  1   [internal]:0
      Tightenco\Quicksand\DeleteOldSoftDeletes::Tightenco\Quicksand\{closure}("App\Models\Entry")

      +8 vendor frames 
  10  [internal]:0

```

**Comment by bakerkretzmar** [comment]
Technically yes, the order _could_ make a difference. Models are deleted in the order they are listed.

If you have foreign key constraints like that you'll probably need to delete the child records first, or manually delete records using a query that ignores or cascades to the children.

If you're on a recent version of Laravel you may be able to accomplish this with the framework's built-in functionality for [Pruning Models](https://laravel.com/docs/8.x/eloquent#pruning-models), which basically replaces this package.
